
version: "3"

services:

  mongo:
    image: mongo:3.6-jessie
    volumes:
      - mongo-data:/data/

  eventcapture:
    build: .
    environment:
      FLASK_APP: /code/eventcapture/app.py
    command: flask run --host 0.0.0.0 -p 5000 --reload
    links:
      - mongo
    volumes:
      - .:/code
    ports:
      - 5000:5000

volumes:
  mongo-data:
